export * from './acct.service';
import { AcctService } from './acct.service';
export * from './assets.service';
import { AssetsService } from './assets.service';
export * from './batches.service';
import { BatchesService } from './batches.service';
export * from './customers.service';
import { CustomersService } from './customers.service';
export * from './deliveryNotes.service';
import { DeliveryNotesService } from './deliveryNotes.service';
export * from './files.service';
import { FilesService } from './files.service';
export * from './invoices.service';
import { InvoicesService } from './invoices.service';
export * from './machines.service';
import { MachinesService } from './machines.service';
export * from './manufactureOrders.service';
import { ManufactureOrdersService } from './manufactureOrders.service';
export * from './manufactureTrackingLogs.service';
import { ManufactureTrackingLogsService } from './manufactureTrackingLogs.service';
export * from './materials.service';
import { MaterialsService } from './materials.service';
export * from './oil.service';
import { OilService } from './oil.service';
export * from './orders.service';
import { OrdersService } from './orders.service';
export * from './outsourcingOrders.service';
import { OutsourcingOrdersService } from './outsourcingOrders.service';
export * from './pkgMaterial.service';
import { PkgMaterialService } from './pkgMaterial.service';
export * from './printers.service';
import { PrintersService } from './printers.service';
export * from './products.service';
import { ProductsService } from './products.service';
export * from './purchasingOrders.service';
import { PurchasingOrdersService } from './purchasingOrders.service';
export * from './reSales.service';
import { ReSalesService } from './reSales.service';
export * from './shipmentRequests.service';
import { ShipmentRequestsService } from './shipmentRequests.service';
export * from './stockCells.service';
import { StockCellsService } from './stockCells.service';
export * from './stockChanges.service';
import { StockChangesService } from './stockChanges.service';
export * from './suppliers.service';
import { SuppliersService } from './suppliers.service';
export * from './tools.service';
import { ToolsService } from './tools.service';
export * from './urlResolver.service';
import { UrlResolverService } from './urlResolver.service';
export * from './zaka.service';
import { ZakaService } from './zaka.service';
export const APIS = [AcctService, AssetsService, BatchesService, CustomersService, DeliveryNotesService, FilesService, InvoicesService, MachinesService, ManufactureOrdersService, ManufactureTrackingLogsService, MaterialsService, OilService, OrdersService, OutsourcingOrdersService, PkgMaterialService, PrintersService, ProductsService, PurchasingOrdersService, ReSalesService, ShipmentRequestsService, StockCellsService, StockChangesService, SuppliersService, ToolsService, UrlResolverService, ZakaService];
