/**
 * ICNC.ERP.Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { TaxType } from './taxType';
import { Currency } from './currency';
import { PaymentType } from './paymentType';


export interface AcctOption { 
    currency: Currency;
    exchange_rate: number;
    tax_rate: number;
    tax_type: TaxType;
    payment_type?: PaymentType;
    bank?: string | null;
    account?: string | null;
    vat_no?: string | null;
}
export namespace AcctOption {
}


