/**
 * ICNC.ERP.Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type ASSETTYPE = 'asset' | 'product' | 'semiFinishedProduct' | 'rawMaterial' | 'tool' | 'gauge' | 'oil' | 'zaka' | 'pkgMaterial';

export const ASSETTYPE = {
    Asset: 'asset' as ASSETTYPE,
    Product: 'product' as ASSETTYPE,
    SemiFinishedProduct: 'semiFinishedProduct' as ASSETTYPE,
    RawMaterial: 'rawMaterial' as ASSETTYPE,
    Tool: 'tool' as ASSETTYPE,
    Gauge: 'gauge' as ASSETTYPE,
    Oil: 'oil' as ASSETTYPE,
    Zaka: 'zaka' as ASSETTYPE,
    PkgMaterial: 'pkgMaterial' as ASSETTYPE
};

