/**
 * ICNC.ERP.Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { DocType } from './docType';


export interface AutolivDoc { 
    version?: string | null;
    fileName?: string | null;
    programCode?: string | null;
    machineCode?: string | null;
    workflowMetaId?: number | null;
    entryTime?: string;
    readonly productId?: string;
    type?: DocType;
}
export namespace AutolivDoc {
}


