/**
 * ICNC.ERP.Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { BatchStockRecord } from './batchStockRecord';
import { StockTransfer } from './stockTransfer';
import { Asset } from './asset';
import { BatchState } from './batchState';
import { Supplier } from './supplier';
import { HFile } from './hFile';
import { ManufactureTrace } from './manufactureTrace';


export interface Batch { 
    id?: string;
    assetId?: string;
    asset?: Asset;
    serialNumber?: string | null;
    heatNumber?: string | null;
    quantity?: number;
    unitPrice?: number;
    readonly quantityBalanced?: number;
    readonly sourceId?: string | null;
    readonly stockTransfers?: Array<StockTransfer> | null;
    readonly stockDetails?: Array<BatchStockRecord> | null;
    readonly stockQuantity?: { [key: string]: number; } | null;
    entryTime?: string;
    remark?: string | null;
    state?: BatchState;
    supplierId?: string | null;
    supplier?: Supplier;
    readonly photos?: Array<HFile> | null;
    readonly certifications?: Array<HFile> | null;
    readonly stockEntries?: { [key: string]: number; } | null;
    plainTrace?: ManufactureTrace;
}
export namespace Batch {
}


