/**
 * ICNC.ERP.Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type BatchState = 'active' | 'inActive' | 'closed';

export const BatchState = {
    Active: 'active' as BatchState,
    InActive: 'inActive' as BatchState,
    Closed: 'closed' as BatchState
};

