/**
 * ICNC.ERP.Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PurchasingOrderItemDto } from './purchasingOrderItemDto';
import { AcctOption } from './acctOption';


export interface CreatePurchasingOrderCommand { 
    acct: AcctOption;
    supplier_id: string;
    order_items: Array<PurchasingOrderItemDto>;
    remark?: string | null;
    source: Array<number>;
}

