/**
 * ICNC.ERP.Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { UNIT } from './uNIT';


export interface CreatePurchasingRequestItemDto { 
    asset_id: string;
    suppliers: Array<string>;
    quantity: number;
    unit_price: number;
    unit: UNIT;
    delivery_item?: string;
    remark?: string | null;
}
export namespace CreatePurchasingRequestItemDto {
}


