/**
 * ICNC.ERP.Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { SpecRecordDto } from './specRecordDto';
import { MATERIAL } from './mATERIAL';
import { FINISH } from './fINISH';


export interface CreateProductCommand { 
    code: string;
    aliases: Array<string>;
    name: string;
    customer_ids: Array<string>;
    finish?: FINISH;
    material?: MATERIAL;
    remark?: string | null;
    spec_records?: Array<SpecRecordDto> | null;
}
export namespace CreateProductCommand {
}


