/**
 * ICNC.ERP.Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { DeliveryNoteItemDTO } from './deliveryNoteItemDTO';


export interface CreateDeliveryNoteCommand { 
    customer_id?: string;
    readonly delivery_note_number?: string | null;
    items?: Array<DeliveryNoteItemDTO> | null;
}

