/**
 * ICNC.ERP.Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { InvoiceDto } from './invoiceDto';
import { CheckSourceType } from './checkSourceType';


export interface CreateEntryFromChecklistItemsCommand { 
    tax_rate: number;
    amount: number;
    source: CheckSourceType;
    checklist_item_ids: Array<number>;
    invoice: InvoiceDto;
    entry_time_text: string;
    invoice_filename: string;
}
export namespace CreateEntryFromChecklistItemsCommand {
}


