/**
 * ICNC.ERP.Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ActionType } from './actionType';
import { UNIT } from './uNIT';
import { ExtraTag } from './extraTag';


export interface CreateManufactureTrackingLogEntryCommand { 
    log_id: number;
    entry_meta_id: number;
    quantity: number;
    weight?: number | null;
    ok_qty: number;
    ng_qty: number;
    mfg_order_number: string;
    remark?: string | null;
    extra?: ExtraTag;
    action: ActionType;
    machine_code?: string | null;
    unit: UNIT;
}
export namespace CreateManufactureTrackingLogEntryCommand {
}


