/**
 * ICNC.ERP.Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface CreateManufactureOrderCommand { 
    order_number?: string | null;
    product_id?: string;
    quantity?: number;
    machine_codes?: Array<string> | null;
    deadline?: string;
    remark?: string | null;
}

