/**
 * ICNC.ERP.Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { OrderItemDto } from './orderItemDto';
import { AcctOption } from './acctOption';


export interface CreateOrderCommand { 
    customer_id: string;
    customer_name?: string | null;
    acct?: AcctOption;
    order_items: Array<OrderItemDto>;
}

