/**
 * ICNC.ERP.Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ActionType } from './actionType';


export interface CreateManufactureTrackingLogEntryGroupCommand { 
    entry_ids: Array<number>;
    action: ActionType;
}
export namespace CreateManufactureTrackingLogEntryGroupCommand {
}


