/**
 * ICNC.ERP.Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { DeliveryStockRecord } from './deliveryStockRecord';


export interface DeliveryNoteItem { 
    id?: string;
    readonly deliveryNoteId?: string;
    index?: number;
    customerOrderNumber?: string | null;
    serialNumber?: string | null;
    orderItemId?: string;
    readonly productId?: string;
    readonly productName?: string | null;
    readonly unitPrice?: number | null;
    readonly quantity?: number;
    readonly amount?: number;
    description?: string | null;
    stockRecords?: Array<DeliveryStockRecord> | null;
    readonly checked?: boolean;
}

