/**
 * ICNC.ERP.Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { BatchStockRecordDTO } from './batchStockRecordDTO';


export interface DeliveryNoteItemDTO { 
    records?: Array<BatchStockRecordDTO> | null;
    shipment_request_id?: string;
    product_id?: string;
    product_name?: string | null;
}

