/**
 * ICNC.ERP.Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type DocType = 'crafts' | 'program' | 'processFlow' | 'toolBom' | 'deviceOperation' | 'maintenance' | 'productInspection' | 'inspectorOperation' | 'inspectorCheck' | 'inspectException' | 'ngHistory' | 'spotCheckTable' | 'machineMaintenanceTable' | 'inspectionSelfCheck' | 'spotCheckInstruction' | 'digitalMicroMeter' | 'airGauge' | 'profiler' | 'projector';

export const DocType = {
    Crafts: 'crafts' as DocType,
    Program: 'program' as DocType,
    ProcessFlow: 'processFlow' as DocType,
    ToolBom: 'toolBom' as DocType,
    DeviceOperation: 'deviceOperation' as DocType,
    Maintenance: 'maintenance' as DocType,
    ProductInspection: 'productInspection' as DocType,
    InspectorOperation: 'inspectorOperation' as DocType,
    InspectorCheck: 'inspectorCheck' as DocType,
    InspectException: 'inspectException' as DocType,
    NgHistory: 'ngHistory' as DocType,
    SpotCheckTable: 'spotCheckTable' as DocType,
    MachineMaintenanceTable: 'machineMaintenanceTable' as DocType,
    InspectionSelfCheck: 'inspectionSelfCheck' as DocType,
    SpotCheckInstruction: 'spotCheckInstruction' as DocType,
    DigitalMicroMeter: 'digitalMicroMeter' as DocType,
    AirGauge: 'airGauge' as DocType,
    Profiler: 'profiler' as DocType,
    Projector: 'projector' as DocType
};

