/**
 * ICNC.ERP.Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type DrawingType = 'internal' | 'customer' | 'internal3d' | 'toolPath' | 'nc' | 'processTesting' | 'qualityTesting' | 'ppap' | 'ngRecord' | 'icncFA' | 'customerFA';

export const DrawingType = {
    Internal: 'internal' as DrawingType,
    Customer: 'customer' as DrawingType,
    Internal3d: 'internal3d' as DrawingType,
    ToolPath: 'toolPath' as DrawingType,
    Nc: 'nc' as DrawingType,
    ProcessTesting: 'processTesting' as DrawingType,
    QualityTesting: 'qualityTesting' as DrawingType,
    Ppap: 'ppap' as DrawingType,
    NgRecord: 'ngRecord' as DrawingType,
    IcncFa: 'icncFA' as DrawingType,
    CustomerFa: 'customerFA' as DrawingType
};

