/**
 * ICNC.ERP.Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type FINISH = 'nature' | 'natureWithAntiRustOil' | 'grindWithAntiRustOil' | 'hexavalentWhiteZinc' | 'trivalentWhiteZincRohs' | 'hexavalentColorZinc' | 'trivalentColorZincRohs' | 'trivalentBlackZincRohs' | 'blacken' | 'nickelPlatingRohs' | 'silver' | 'blunt' | 'nylokPatch' | 'whiteZincNylokPatch' | 'blackenNylokPatch' | 'qpq' | 'sandblasting' | 'paintBlack' | 'paintGray' | 'paintRed' | 'oxidativeBlacken' | 'phosphating';

export const FINISH = {
    Nature: 'nature' as FINISH,
    NatureWithAntiRustOil: 'natureWithAntiRustOil' as FINISH,
    GrindWithAntiRustOil: 'grindWithAntiRustOil' as FINISH,
    HexavalentWhiteZinc: 'hexavalentWhiteZinc' as FINISH,
    TrivalentWhiteZincRohs: 'trivalentWhiteZincRohs' as FINISH,
    HexavalentColorZinc: 'hexavalentColorZinc' as FINISH,
    TrivalentColorZincRohs: 'trivalentColorZincRohs' as FINISH,
    TrivalentBlackZincRohs: 'trivalentBlackZincRohs' as FINISH,
    Blacken: 'blacken' as FINISH,
    NickelPlatingRohs: 'nickelPlatingRohs' as FINISH,
    Silver: 'silver' as FINISH,
    Blunt: 'blunt' as FINISH,
    NylokPatch: 'nylokPatch' as FINISH,
    WhiteZincNylokPatch: 'whiteZincNylokPatch' as FINISH,
    BlackenNylokPatch: 'blackenNylokPatch' as FINISH,
    Qpq: 'qpq' as FINISH,
    Sandblasting: 'sandblasting' as FINISH,
    PaintBlack: 'paintBlack' as FINISH,
    PaintGray: 'paintGray' as FINISH,
    PaintRed: 'paintRed' as FINISH,
    OxidativeBlacken: 'oxidativeBlacken' as FINISH,
    Phosphating: 'phosphating' as FINISH
};

