/**
 * ICNC.ERP.Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { BatchSourceType } from './batchSourceType';


export interface GenerateBatchSerialNumberCommand { 
    source_type: BatchSourceType;
    order_id: string;
}
export namespace GenerateBatchSerialNumberCommand {
}


