/**
 * ICNC.ERP.Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type HEATTREATMENT = 'raw' | 'temper' | 'carbonize' | 'highFrequencyProcess' | 'anneal' | 'nitridize';

export const HEATTREATMENT = {
    Raw: 'raw' as HEATTREATMENT,
    Temper: 'temper' as HEATTREATMENT,
    Carbonize: 'carbonize' as HEATTREATMENT,
    HighFrequencyProcess: 'highFrequencyProcess' as HEATTREATMENT,
    Anneal: 'anneal' as HEATTREATMENT,
    Nitridize: 'nitridize' as HEATTREATMENT
};

