/**
 * ICNC.ERP.Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type Industry = 'unKnown' | 'aerospace' | 'car' | 'electroMechanical' | 'electrical' | 'mechanical';

export const Industry = {
    UnKnown: 'unKnown' as Industry,
    Aerospace: 'aerospace' as Industry,
    Car: 'car' as Industry,
    ElectroMechanical: 'electroMechanical' as Industry,
    Electrical: 'electrical' as Industry,
    Mechanical: 'mechanical' as Industry
};

