/**
 * ICNC.ERP.Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { InvoiceQrCodeContent } from './invoiceQrCodeContent';


export interface InvoiceResolveResultDTO { 
    content?: InvoiceQrCodeContent;
    url?: string | null;
    fileName?: string | null;
}

