/**
 * ICNC.ERP.Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { MFGORDERSTATE } from './mFGORDERSTATE';
import { ManufactureConsumeEntry } from './manufactureConsumeEntry';
import { Batch } from './batch';
import { ManufactureLogEntry } from './manufactureLogEntry';
import { WorkflowEntryMeta } from './workflowEntryMeta';
import { Supplier } from './supplier';


export interface ManufactureOrder { 
    id?: string;
    orderNumber?: string | null;
    productId?: string;
    machines?: Set<string> | null;
    manufactureNumber?: number;
    description?: string | null;
    readonly logEntries?: Array<ManufactureLogEntry> | null;
    readonly consumeEntries?: Array<ManufactureConsumeEntry> | null;
    readonly supplierId?: string | null;
    supplier?: Supplier;
    readonly isOutsourcing?: boolean;
    readonly numberBalanced?: number;
    deliveryTime?: string;
    lastModifiedTime?: string;
    creationTime?: string;
    state?: MFGORDERSTATE;
    createFromBatch?: boolean;
    batchId?: string | null;
    batch?: Batch;
    heatNumber?: string | null;
    serialNumber?: string | null;
    workflowEntryMetaId?: number | null;
    workflowEntryMeta?: WorkflowEntryMeta;
}
export namespace ManufactureOrder {
}


