/**
 * ICNC.ERP.Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Shift } from './shift';
import { Product } from './product';
import { Machine } from './machine';
import { ManufactureOrder } from './manufactureOrder';


export interface ManufactureLogEntry { 
    id?: string;
    mfgOrderId?: string;
    order?: ManufactureOrder;
    shift?: Shift;
    weight?: number;
    number?: number;
    productId?: string;
    product?: Product;
    readonly productName?: string | null;
    machineId?: string | null;
    machine?: Machine;
    entryTime?: string;
    creationTime?: string;
    checked?: boolean;
}

