/**
 * ICNC.ERP.Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ManufactureTrackingLogEntryDto } from './manufactureTrackingLogEntryDto';


export interface ManufactureTrackingLogDto { 
    id: number;
    entries: Array<ManufactureTrackingLogEntryDto>;
    batch_id: string;
    serial_number?: string | null;
    heat_number?: string | null;
    product_id?: string | null;
    product_name?: string | null;
    quantity: number;
    weight?: number | null;
    failed_quantity?: number | null;
    failed_weight?: number | null;
    remark?: string | null;
}

