/**
 * ICNC.ERP.Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { State } from './state';


export interface ManufactureTrackingLogEntryQueryCommand { 
    state?: State;
    code_or_name_search?: string | null;
    log_number_search?: string | null;
    mfg_order_search?: string | null;
    workflow_entry_name_search?: string | null;
    date_range?: Array<string> | null;
}
export namespace ManufactureTrackingLogEntryQueryCommand {
}


