/**
 * ICNC.ERP.Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { UNIT } from './uNIT';
import { Product } from './product';


export interface ManufactureTrackingData { 
    logId?: number;
    index?: number;
    productId?: string | null;
    entryName?: string | null;
    product?: Product;
    qty?: number;
    okQty?: number | null;
    ngQty?: number | null;
    unit?: UNIT;
}
export namespace ManufactureTrackingData {
}


