/**
 * ICNC.ERP.Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Batch } from './batch';
import { Machine } from './machine';
import { ManufactureOrder } from './manufactureOrder';


export interface ManufactureConsumeEntry { 
    id?: string;
    mfgOrderId?: string;
    order?: ManufactureOrder;
    batchId?: string;
    batch?: Batch;
    machineId?: string | null;
    machine?: Machine;
    quantity?: number;
    unitPrice?: number;
    readonly amount?: number;
    creationTime?: string;
    entryTime?: string;
}

