/**
 * ICNC.ERP.Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type MATERIALSHAPE = 'sheet' | 'hexagonBar' | 'roundBar' | 'squareBar' | 'hexagonPipe' | 'roundPipe' | 'squarePipe' | 'spherical' | 'other' | 'millCoil';

export const MATERIALSHAPE = {
    Sheet: 'sheet' as MATERIALSHAPE,
    HexagonBar: 'hexagonBar' as MATERIALSHAPE,
    RoundBar: 'roundBar' as MATERIALSHAPE,
    SquareBar: 'squareBar' as MATERIALSHAPE,
    HexagonPipe: 'hexagonPipe' as MATERIALSHAPE,
    RoundPipe: 'roundPipe' as MATERIALSHAPE,
    SquarePipe: 'squarePipe' as MATERIALSHAPE,
    Spherical: 'spherical' as MATERIALSHAPE,
    Other: 'other' as MATERIALSHAPE,
    MillCoil: 'millCoil' as MATERIALSHAPE
};

