/**
 * ICNC.ERP.Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type MATERIAL = 'unKnown' | 'lowCarbonSteel' | 'carbonSteel' | 'alloySteel' | 'freeCuttingSteel' | 'bearingSteel' | 'stainlessSteel' | 'rustlessIron' | 'copper' | 'aluminum' | 'nonMetal';

export const MATERIAL = {
    UnKnown: 'unKnown' as MATERIAL,
    LowCarbonSteel: 'lowCarbonSteel' as MATERIAL,
    CarbonSteel: 'carbonSteel' as MATERIAL,
    AlloySteel: 'alloySteel' as MATERIAL,
    FreeCuttingSteel: 'freeCuttingSteel' as MATERIAL,
    BearingSteel: 'bearingSteel' as MATERIAL,
    StainlessSteel: 'stainlessSteel' as MATERIAL,
    RustlessIron: 'rustlessIron' as MATERIAL,
    Copper: 'copper' as MATERIAL,
    Aluminum: 'aluminum' as MATERIAL,
    NonMetal: 'nonMetal' as MATERIAL
};

