/**
 * ICNC.ERP.Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type MFGORDERSTATE = 'started' | 'finished' | 'cancelled' | 'pending' | 'notStarted';

export const MFGORDERSTATE = {
    Started: 'started' as MFGORDERSTATE,
    Finished: 'finished' as MFGORDERSTATE,
    Cancelled: 'cancelled' as MFGORDERSTATE,
    Pending: 'pending' as MFGORDERSTATE,
    NotStarted: 'notStarted' as MFGORDERSTATE
};

