/**
 * ICNC.ERP.Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface MtEntryLabelCommand { 
    log_id: number;
    index: number;
    entry_name: string;
    times: number;
    machine_code?: string | null;
    quantity?: number;
    ok_quantity?: number;
    ng_quantity?: number;
    printer_name?: string | null;
}

