/**
 * ICNC.ERP.Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { ExtraTag } from './extraTag';


export interface MtEntryKey { 
    logId?: number;
    index?: number;
    machineCode?: string | null;
    dateString?: string | null;
    shift?: ExtraTag;
}
export namespace MtEntryKey {
}


