/**
 * ICNC.ERP.Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { OutsourcingOrderItemConsumeEntry } from './outsourcingOrderItemConsumeEntry';
import { UNIT } from './uNIT';
import { OutsourcingItemReceiveRecord } from './outsourcingItemReceiveRecord';
import { OutsourcingItemReturnRecord } from './outsourcingItemReturnRecord';
import { PROCESSINGTYPE } from './pROCESSINGTYPE';
import { OutsourcingType } from './outsourcingType';


export interface OutsourcingOrderItem { 
    id?: string;
    type?: OutsourcingType;
    orderId?: string;
    index?: number;
    processingType?: PROCESSINGTYPE;
    readonly assetIdSrc?: string;
    readonly assetIdDst?: string;
    unitOfCharge?: UNIT;
    readonly unitPrice?: number;
    readonly unitPriceCharge?: number;
    readonly quantityOfCharge?: number;
    unit?: UNIT;
    quantity?: number;
    readonly quantityOut?: number;
    readonly quantityCancelled?: number;
    readonly quantityBalanced?: number;
    readonly quantityReceived?: number;
    readonly quantityReturned?: number;
    creationTime?: string;
    lastModifiedTime?: string;
    readonly consumeEntries?: Array<OutsourcingOrderItemConsumeEntry> | null;
    readonly returnRecords?: Array<OutsourcingItemReturnRecord> | null;
    readonly receiveRecords?: Array<OutsourcingItemReceiveRecord> | null;
    remark?: string | null;
    readonly deliveryTime?: string | null;
    readonly closed?: boolean;
}
export namespace OutsourcingOrderItem {
}


