/**
 * ICNC.ERP.Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { OutsourcingOrderItem } from './outsourcingOrderItem';
import { Supplier } from './supplier';
import { OsState } from './osState';


export interface OutsourcingOrder { 
    id?: string;
    state?: OsState;
    orderNumber?: string | null;
    readonly isRework?: boolean;
    supplierId?: string;
    supplier?: Supplier;
    creationTime?: string;
    lastModifiedTime?: string;
    readonly items?: Array<OutsourcingOrderItem> | null;
    remark?: string | null;
    creator?: string | null;
}
export namespace OutsourcingOrder {
}


