/**
 * ICNC.ERP.Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { UNIT } from './uNIT';
import { OutsourcingOrderItemStockOutRecord } from './outsourcingOrderItemStockOutRecord';
import { PROCESSINGTYPE } from './pROCESSINGTYPE';


export interface OutsourcingItemDTO { 
    index: number;
    process_type: PROCESSINGTYPE;
    asset_id_before: string;
    asset_id_after: string;
    unit_charge: UNIT;
    unit_price_charge: number;
    quantity_of_charge: number;
    quantity: number;
    quantity_out: number;
    remark?: string | null;
    stock_out_records?: Array<OutsourcingOrderItemStockOutRecord> | null;
    delivery_time: string;
}
export namespace OutsourcingItemDTO {
}


