/**
 * ICNC.ERP.Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface PatrolSelfTableDto { 
    dimension?: string | null;
    patrol?: string | null;
    minVal?: string | null;
    maxVal?: string | null;
    measureTool?: string | null;
    item1?: string | null;
    item2?: string | null;
    item3?: string | null;
    item4?: string | null;
    item5?: string | null;
    item6?: string | null;
}

