/**
 * ICNC.ERP.Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type PoState = 'cancelled' | 'closed' | 'waitingForApprovement' | 'approved' | 'waitingForCheck' | 'checked';

export const PoState = {
    Cancelled: 'cancelled' as PoState,
    Closed: 'closed' as PoState,
    WaitingForApprovement: 'waitingForApprovement' as PoState,
    Approved: 'approved' as PoState,
    WaitingForCheck: 'waitingForCheck' as PoState,
    Checked: 'checked' as PoState
};

