/**
 * ICNC.ERP.Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { STOCKTYPE } from './sTOCKTYPE';


export interface PrintBatchLabelCommand { 
    id: string;
    times: number;
    quantity?: number;
    printer_name?: string | null;
    stock_name?: STOCKTYPE;
    product_alias?: string | null;
}
export namespace PrintBatchLabelCommand {
}


