/**
 * ICNC.ERP.Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Drawing } from './drawing';
import { UNIT } from './uNIT';
import { ASSETTYPE } from './aSSETTYPE';
import { SpecRecord } from './specRecord';
import { AutolivDoc } from './autolivDoc';
import { MATERIAL } from './mATERIAL';
import { SemiFinishedProduct } from './semiFinishedProduct';
import { FINISH } from './fINISH';
import { HEATTREATMENT } from './hEATTREATMENT';
import { WorkflowMeta } from './workflowMeta';


export interface Product { 
    id?: string;
    assetType?: ASSETTYPE;
    code?: string | null;
    unit?: UNIT;
    name?: string | null;
    creationTime?: string;
    readonly lastModifiedTime?: string;
    specifications?: Set<SpecRecord> | null;
    readonly nickName?: string | null;
    remark?: string | null;
    isDeleted?: boolean;
    aliases?: Set<string> | null;
    material?: MATERIAL;
    materialDescription?: string | null;
    finish?: FINISH;
    finishDescription?: string | null;
    heatTreatment?: HEATTREATMENT;
    heatTreatmentDescription?: string | null;
    weight?: number | null;
    readonly semis?: Array<SemiFinishedProduct> | null;
    readonly drawings?: Array<Drawing> | null;
    readonly documents?: Array<AutolivDoc> | null;
    avatar?: string | null;
    readonly customerDrawing?: string | null;
    readonly internalDrawing?: string | null;
    readonly internal3dDrawing?: string | null;
    readonly toolPathDrawing?: string | null;
    readonly ncDrawing?: string | null;
    readonly processRecord?: string | null;
    readonly productTesting?: string | null;
    readonly ppapDrawing?: string | null;
    readonly ngRecord?: string | null;
    readonly icncFA?: string | null;
    readonly customerFA?: string | null;
    workflowMetas?: Array<WorkflowMeta> | null;
}
export namespace Product {
}


