/**
 * ICNC.ERP.Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { MATERIAL } from './mATERIAL';
import { FINISH } from './fINISH';


export interface ProductDto { 
    id: string;
    code: string;
    name: string;
    finish: FINISH;
    material: MATERIAL;
}
export namespace ProductDto {
}


