/**
 * ICNC.ERP.Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type RAW = 'carbonSteel' | 'stainlessSteel' | 'copper' | 'aluminum' | 'alloySteel' | 'nonMetal' | 'casting';

export const RAW = {
    CarbonSteel: 'carbonSteel' as RAW,
    StainlessSteel: 'stainlessSteel' as RAW,
    Copper: 'copper' as RAW,
    Aluminum: 'aluminum' as RAW,
    AlloySteel: 'alloySteel' as RAW,
    NonMetal: 'nonMetal' as RAW,
    Casting: 'casting' as RAW
};

