/**
 * ICNC.ERP.Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { RAW } from './rAW';
import { SpecRecordDto } from './specRecordDto';
import { MATERIALSHAPE } from './mATERIALSHAPE';


export interface RawMaterialDto { 
    id: string;
    code: string;
    name: string;
    shape: MATERIALSHAPE;
    raw: RAW;
    records: Array<SpecRecordDto>;
}
export namespace RawMaterialDto {
}


