/**
 * ICNC.ERP.Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { Supplier } from './supplier';
import { AcctOption } from './acctOption';
import { ReSaleItem } from './reSaleItem';


export interface ReSale { 
    id?: string;
    acct?: AcctOption;
    orderNumber?: string | null;
    supplier?: Supplier;
    supplierId?: string;
    supplierName?: string | null;
    creationTime?: string;
    readonly lastModifiedTime?: string;
    readonly items?: Array<ReSaleItem> | null;
    remark?: string | null;
}

