/**
 * ICNC.ERP.Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { OrderItem } from './orderItem';
import { Product } from './product';


export interface ShipmentRequest { 
    id?: string;
    orderItem?: OrderItem;
    orderItemId?: string;
    productId?: string;
    productName?: string | null;
    product?: Product;
    unitPrice?: number;
    readonly quantityRequested?: number;
    readonly quantityShipped?: number;
    readonly isClosed?: boolean;
    readonly shipmentLast?: string | null;
    creationTime?: string;
    readonly lastModifiedTime?: string;
    remark?: string | null;
}

