/**
 * ICNC.ERP.Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type State = 'init' | 'reported' | 'inspected' | 'checked' | 'closed' | 'deleted';

export const State = {
    Init: 'init' as State,
    Reported: 'reported' as State,
    Inspected: 'inspected' as State,
    Checked: 'checked' as State,
    Closed: 'closed' as State,
    Deleted: 'deleted' as State
};

