/**
 * ICNC.ERP.Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { PLANTTYPE } from './pLANTTYPE';
import { STOCKTYPE } from './sTOCKTYPE';


export interface StockCell { 
    id?: string;
    code?: string | null;
    type?: STOCKTYPE;
    name?: string | null;
    plantType?: PLANTTYPE;
    isDeleted?: boolean;
}
export namespace StockCell {
}


