/**
 * ICNC.ERP.Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { StockChangeBase } from './stockChangeBase';


export interface StockChangeChecklistItem { 
    readonly id?: number;
    stockChangeId?: number;
    stockChangeBase?: StockChangeBase;
    quantity?: number;
    unitPrice?: number;
    readonly amount?: number;
    dateTime?: string;
    stockChangeTime?: string;
    readonly closed?: boolean;
    userName?: string | null;
}

