/**
 * ICNC.ERP.Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { TransferStockOutRecord } from './transferStockOutRecord';
import { TransferStockInRecord } from './transferStockInRecord';


export interface StockTransfer { 
    readonly id?: number;
    creationTime?: string;
    outEntries?: Set<TransferStockOutRecord> | null;
    inEntries?: Set<TransferStockInRecord> | null;
    readonly quantity?: number;
}

