/**
 * ICNC.ERP.Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type StockChangeHint = 'purchasingStockIn' | 'purchasingReturnStockOut' | 'outsourcingStockIn' | 'outsourcingStockOut' | 'outsourcingReturnStockOut' | 'manufactureStockIn' | 'manufactureConsumeStockOut' | 'manufactureReturnStockIn' | 'salesStockOut' | 'salesReturnStockIn' | 'transferStockIn' | 'transferStockOut' | 'stockChangeLossAndProfit' | 'reSale' | 'openingStockIn' | 'generalConsumeStockOut';

export const StockChangeHint = {
    PurchasingStockIn: 'purchasingStockIn' as StockChangeHint,
    PurchasingReturnStockOut: 'purchasingReturnStockOut' as StockChangeHint,
    OutsourcingStockIn: 'outsourcingStockIn' as StockChangeHint,
    OutsourcingStockOut: 'outsourcingStockOut' as StockChangeHint,
    OutsourcingReturnStockOut: 'outsourcingReturnStockOut' as StockChangeHint,
    ManufactureStockIn: 'manufactureStockIn' as StockChangeHint,
    ManufactureConsumeStockOut: 'manufactureConsumeStockOut' as StockChangeHint,
    ManufactureReturnStockIn: 'manufactureReturnStockIn' as StockChangeHint,
    SalesStockOut: 'salesStockOut' as StockChangeHint,
    SalesReturnStockIn: 'salesReturnStockIn' as StockChangeHint,
    TransferStockIn: 'transferStockIn' as StockChangeHint,
    TransferStockOut: 'transferStockOut' as StockChangeHint,
    StockChangeLossAndProfit: 'stockChangeLossAndProfit' as StockChangeHint,
    ReSale: 'reSale' as StockChangeHint,
    OpeningStockIn: 'openingStockIn' as StockChangeHint,
    GeneralConsumeStockOut: 'generalConsumeStockOut' as StockChangeHint
};

