/**
 * ICNC.ERP.Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { AcctOption } from './acctOption';
import { Contact } from './contact';


export interface Supplier { 
    id?: string;
    code?: string | null;
    supplierName?: string | null;
    acct?: AcctOption;
    address?: string | null;
    nickName?: string | null;
    creationTime?: string;
    readonly lastModifiedTime?: string;
    contacts?: Array<Contact> | null;
}

