/**
 * ICNC.ERP.Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export type TaxType = 'y' | 'n' | 'zero';

export const TaxType = {
    Y: 'y' as TaxType,
    N: 'n' as TaxType,
    Zero: 'zero' as TaxType
};

