/**
 * ICNC.ERP.Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { StockChangeChecklistItem } from './stockChangeChecklistItem';
import { StockCell } from './stockCell';
import { StockChangeHint } from './stockChangeHint';
import { StockChangeType } from './stockChangeType';


export interface TransferStockInRecord { 
    readonly id?: number;
    readonly batchId?: string;
    readonly serialNumber?: string | null;
    readonly stockId?: string;
    stockCell?: StockCell;
    stockName?: string | null;
    readonly quantity?: number;
    creationTime?: string;
    readonly lastModifiedTime?: string;
    remark?: string | null;
    checked?: boolean;
    stockChangeChecklistItem?: StockChangeChecklistItem;
    type?: StockChangeType;
    readonly transferId?: number | null;
    hint?: StockChangeHint;
}
export namespace TransferStockInRecord {
}


