/**
 * ICNC.ERP.Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */
import { SpecRecordDto } from './specRecordDto';
import { MATERIAL } from './mATERIAL';
import { FINISH } from './fINISH';
import { HEATTREATMENT } from './hEATTREATMENT';


export interface UpdateProductCommand { 
    product_id: string;
    aliases: Array<string>;
    net_weight?: number | null;
    customers?: Array<string> | null;
    name?: string | null;
    nick_name?: string | null;
    finish?: FINISH;
    finish_description?: string | null;
    material?: MATERIAL;
    material_description?: string | null;
    heat_treatment?: HEATTREATMENT;
    heat_treatment_description?: string | null;
    spec_records?: Array<SpecRecordDto> | null;
    remark?: string | null;
}
export namespace UpdateProductCommand {
}


