/**
 * ICNC.ERP.Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface UpdateOutSourcingCommand { 
    orderId?: string;
    orderItemId?: string;
    supplierName?: string | null;
    code?: string | null;
    processType?: string | null;
    quantity?: number;
    remark?: string | null;
    unitPrice?: number;
}

