/**
 * ICNC.ERP.Api
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: v1
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


export interface UpdateSupplierCommand { 
    id?: string;
    code?: string | null;
    name?: string | null;
    nickName?: string | null;
    address?: string | null;
    bankName?: string | null;
    bankAccount?: string | null;
    vatNumber?: string | null;
    taxRate?: number;
    contactName?: string | null;
    contactPhone?: string | null;
}

